name: wedzera
description: >-
  Wedzera is a tool library for Flutter and Dart.
version: 1.0.0
homepage: https://github.com/nikeorever/wedzera

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: ^1.14.12

dev_dependencies:
  benchmark_harness: ^1.0.5
  pedantic: ^1.8.0
  test: ^1.6.0
