name: wedzera
description: >-
  Wedzera is an extension toolkit for Dart, It contains many convenient, functional, and easy-to-use functions.
version: 0.0.2
homepage: https://github.com/nikeorever/wedzera

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  quiver: ^2.1.3
  collection: ^1.14.12

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  benchmark_harness: ^1.0.5
